### PR TITLE
fix the issue (#198) that loop closures can rotate the map 180° if the lidar is mounted backwards

### LINKED ISSUE #198: [rplidar users] Potential errors with drivers + 360 lidar support
**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - from source
- ROS Version
  - ROS Kinetic
- Version or commit hash:
  - kinetic-devel, latest commit (9b14cf8369a63264fd9935be4cca5cf14386bfc5)

#### Steps to reproduce issue
I created a minimal repo with bags, config and launch files:  
https://github.com/saschroeder/turtlebot_slam_testing  

The bug always occurs with rosbags and sometimes in simulation, too. Disabling loop closure prevents the bug.   
I can upload more rosbags if necessary.

#### Expected behavior
Record an accurate map and correctly use loop closure to improve the map.

#### Actual behavior
After some time the map is rotated around 180° (may be related or not) and some time after this (seconds to minutes) the pose graph is optimized in a wrong way, causing the map to be broken (see images below).  

#### Additional information

Example 1 (before/after optimization):  
ex1_before_optimization
ex1_after_optimization

Example 2 (before/ after optimization):
ex2_before_optimization
ex2_after_optimization

### PR DESCRIPTION
**Pull request by WLwind**
Set the edges (constraints) based on the robot base frame (base_footprint) instead of sensor frame (laser).

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (#198 ) |
| Primary OS tested on | (Ubuntu 20.04 ROS Noetic and Ubuntu 18.04 ROS Melodic) |
| Robotic platform tested on | ([Handsfree mini](https://github.com/HANDS-FREE/handsfree.git) with RPLIDAR A2 mounted backwards) |

---

## Description of contribution in a few bullet points

The reason of weird results of loop closures when lidars are mounted backwards is that the vertices and the edges of the solver are not based on the same frame. The original code sets the pose of the base link (base_footprint) as the vertex pose, but the edges are constraints of 2 poses of sensor frame (laser). That's really unreasonable because the tf between base poses and the tf between their corresponding sensor poses are not the same! The differences are significantly big especially when the sensor is at the opposite orientation of the robot base. So this uncommon loop closure will always happen (more or less) unless the sensor frame is at the exact pose of the base. This is regardless of whether the lidar is 360° or whether it's an RPLIDAR.

I made the edges and vertices based on the same frame. I simply set the edges (constraints) based on the robot base frame (base_footprint) instead of sensor frame (laser).
It works well with my backwards mounted RPLIDAR A2.
## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

I don't have a ROS2 robot yet. Is anyone there be kind to test this modification on a ROS2 robot?

### CODE REVIEW

**Comment by SteveMacenski** [comment]
So by backwards, you do not mean up-side down, correct? By the way, just going to chat on this PR since all the others are the same, I'll just merge them all at once but use this as the proxy.

https://github.com/SteveMacenski/slam_toolbox/issues/198#issuecomment-622651356 <-- Can you show that you can work on this dataset and have it work? They give a pretty good backwards-lidar dataset here. [We resolved this by changing a loss function](https://github.com/SteveMacenski/slam_toolbox/issues/198#issuecomment-666526810), so please make sure you **don't** use that one for your testing to show that it also fixes the issue (and does so more reliably).  

So I think we're getting more to the root of all these rplidar problems then. It sounds like there were CPU (fixed), backwards (or rather, non-directionally aligned), and 360 param read in wrong (fixed). There's also this "flipping" problem only 360 lidar users report (#281) that I also wonder if this would fix if this indeed is a functional solution... (also makes me wonder if this was my issue with the multi-lidar support testing... mhm...). It would be mighty convenient if this fixed that too. I've never been able to replicate on professional 270 lidars so its been hard for me to be able to spend the time to fix it. Something along these lines could be the root cause or at least a new way of thinking I can use to see if I can spot other locations in the Karto code this is wrong. 

I'll review in a moment. I **super** appreciate you digging into this code. It's been hard to fix all these issues without someone else to bounce ideas off of that's dug into the core SLAM code. :clap:

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp [hunk 1]
```diff
@@ -1605,7 +1605,11 @@ namespace karto
     // only attach link information if the edge is new
```
Comment (SteveMacenski) [inline slam_toolbox/lib/karto_sdk/src/Mapper.cpp:1605]: First off, just linting things, place space between the `=` and don't use `auto` since the rest of this file doesn't make use of it for styling consistency.

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp [hunk 2]
```diff
@@ -1605,7 +1605,11 @@ namespace karto
...
     if (isNewEdge == true)
     {
-      pEdge->SetLabel(new LinkInfo(pFromScan->GetSensorPose(), rMean, rCovariance));
+      auto corrected_pose=pToScan->GetCorrectedPose();
+      pToScan->SetSensorPose(rMean);
+      auto corrected_mean_pose=pToScan->GetCorrectedPose();
+      pToScan->SetCorrectedPose(corrected_pose);
```
Comment (SteveMacenski) [inline slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: L1608 is `corrected_pose=pToScan->GetCorrectedPose();` but then you `pToScan->SetCorrectedPose(corrected_pose);`, how is L1611 meaningful? It looks like you just `set` what you `get` without changing.

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp [hunk 3]
```diff
@@ -1605,7 +1605,11 @@ namespace karto
     // only attach link information if the edge is new
     if (isNewEdge == true)
     {
-      pEdge->SetLabel(new LinkInfo(pFromScan->GetSensorPose(), rMean, rCovariance));
+      auto corrected_pose=pToScan->GetCorrectedPose();
```
Comment (SteveMacenski) [inline slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: Please explain the steps here and what's changing - I'm not able to easily follow the logic change here, but my thoughts are below. Also, why not make these changes somewhere higher up in the software, like closer to the process functions? 

AddVertex adds just the entire `pScan` object, so there's no caring about the specific frame of the data. Then the major place its used is in the optimizer (https://github.com/SteveMacenski/slam_toolbox/blob/foxy-devel/solvers/ceres_solver.cpp#L270) which uses the `GetCorrectedPose`'s to operate - so corrected poses.

Then looking at the optimizer's AddConstraints, we see we get the information from https://github.com/SteveMacenski/slam_toolbox/blob/foxy-devel/solvers/ceres_solver.cpp#L309 `GetPoseDifference` which returns the output of `Update` called in the `LinkInfo` constructor using the L1612 inputs. So those inputs should be in the same frame as `AddNode` one way or another. 

So, ok, I can understand then that we either need to change the `AddNode` in the optimizer to use the sensor poses **or** change the edges to use the corrected poses like we give to the `AddNode`. Did you try the 1 line change in the Ceres optimizer first? That would be less changes and I _believe_ it would have the same outcome (though the pose-graph means something slightly different then). 

---

So I'm on the same page about the core problem, though the code you have here is a little confusing to me. Walking me through the specific lines would be helpful and maybe think if this is really the right place for all of it.

**Review by SteveMacenski — CHANGES_REQUESTED** [review]

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp (hunk 2 above)
Comment (WLwind) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: L1609 changes m_CorrectedPose of pToScan. I'm not sure whether the original m_CorrectedPose value is going to be used in processes below, so I simply reset  the m_CorrectedPose of pToScan to make sure every value is the same as the original code before calling pEdge->SetLabel.

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp (hunk 3 above)
Comment (WLwind) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: Yes I have tried that "1 line change" which sets the sensor pose as the vertex node. Everything worked OK until once I tried to deserialize a posegraph file that I have just saved with the save version code. The program threw an exception and died. Maybe it assumes that all the vertices stand for the base poses (I'm not sure about this). So I tried the second way which you can see now.

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp (hunk 1 above)
Comment (WLwind) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp:1605]: I've pushed a new commit.

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp (hunk 3 above)
Comment (SteveMacenski) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: Ok - can you still walk me through these changes then? I'm not following the logic intuitively about what each of these do and why.

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp (hunk 2 above)
Comment (SteveMacenski) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: Can you check and see? From my first glance it looks like it doesn't do anything

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp (hunk 3 above)
Comment (WLwind) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: My goal is to set constraints between 2 base poses instead of sensor poses. Now we need to create a `LinkInfo` object as a label of the edge to link these 2 base poses (L1612). First argument is base pose of `pFromScan` which is `pFromScan->GetCorrectedPose()`. Second argument is not simply base pose of `pToScan` but the `rMean`'s corresponding base pose. As you can see from `MapperGraph::AddEdges` function, `rMean` is a sensor pose. L1609 and L1610 calculate that base pose we need which is passed to `LinkInfo` below. As we have used `pToScan` as a tool to make a transformation (L1609), it changes the original base pose of `pToScan` (in function `LocalizedRangeScan::SetSensorPose` we called in L1609) which I'm not sure will influence the processes below or not. So I decide to reset the original base pose to `pToScan` (L1611) so that every value is the same as the original code except the arguments of `LinkInfo`.
After ceres solver optimizing the pose graph, we need to update the `LocalizedRangeScan`. The optimization result is base poses, so we call `LocalizedRangeScan::SetCorrectedPose` instead of `LocalizedRangeScan::SetSensorPose` (L1995).

**Comment by WLwind** [comment]
> So by backwards, you do not mean up-side down, correct? By the way, just going to chat on this PR since all the others are the same, I'll just merge them all at once but use this as the proxy.
> 
> [#198 (comment)](https://github.com/SteveMacenski/slam_toolbox/issues/198#issuecomment-622651356) <-- Can you show that you can work on this dataset and have it work? They give a pretty good backwards-lidar dataset here. [We resolved this by changing a loss function](https://github.com/SteveMacenski/slam_toolbox/issues/198#issuecomment-666526810), so please make sure you **don't** use that one for your testing to show that it also fixes the issue (and does so more reliably).
> 
> So I think we're getting more to the root of all these rplidar problems then. It sounds like there were CPU (fixed), backwards (or rather, non-directionally aligned), and 360 param read in wrong (fixed). There's also this "flipping" problem only 360 lidar users report (#281) that I also wonder if this would fix if this indeed is a functional solution... (also makes me wonder if this was my issue with the multi-lidar support testing... mhm...). It would be mighty convenient if this fixed that too. I've never been able to replicate on professional 270 lidars so its been hard for me to be able to spend the time to fix it. Something along these lines could be the root cause or at least a new way of thinking I can use to see if I can spot other locations in the Karto code this is wrong.
> 
> I'll review in a moment. I **super** appreciate you digging into this code. It's been hard to fix all these issues without someone else to bounce ideas off of that's dug into the core SLAM code. clap

I've recorded a video of mapping process using #198 dataset.
https://user-images.githubusercontent.com/46443331/106920506-1ef9ef80-6746-11eb-9145-7b2a9c26ff76.mp4
It works pretty well with 18 loop closures.

**Comment by SteveMacenski** [comment]
Thanks for the verification. @coderkarl also verified which is good to have an external thumbs up. I agree this is an issue and now I agree that your solution is workable. Now we're just on the details of making sure this is the right place to put it / if there's a better way to accomplish the same task.

File: slam_toolbox/lib/karto_sdk/src/Mapper.cpp (hunk 3 above)
Comment (SteveMacenski) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: > L1609 and L1610 calculate that base pose we need which is passed to LinkInfo below. 

I totally understand that, but I'm a little concerned by the fact that you're `setting` the pose, overriding whatever was there beforehand to compute this value (though 1611 resets). Would it not be possible to just [transform the data](https://github.com/SteveMacenski/slam_toolbox/blob/b0800ed7e5b1f955386a46a0ac8f9ef159120c13/slam_toolbox/lib/karto_sdk/include/karto_sdk/Karto.h#L5637-L5645) in the same way shown in that function without `Setting` / `Getting`? 

Recommendation: Make [this logic](https://github.com/SteveMacenski/slam_toolbox/blob/b0800ed7e5b1f955386a46a0ac8f9ef159120c13/slam_toolbox/lib/karto_sdk/include/karto_sdk/Karto.h#L5637-L5646) into a function (or maybe an analog function to `GetSensorAt`, `GetCorrectedAt` will work?) that `SetSensorPose` uses. Then make that function public so that in L1609/1610 you can call that to replace the `set` and `get`. Then no data is messed with and we just transform some data. 

---

> So I decide to reset the original base pose to pToScan (L1611) so that every value is the same as the original code except the arguments of LinkInfo.

If you do the recommendation above, then this won't be necessary because you didn't change any of the `pToScan` data. Also its alot more efficient because the `SetSensorPose` calls `Update` which iterates through all the points. 

---

L1995 we're on the same page about, no issue. Really all `SetSensorPose` is doing anyhow is computing the offset value of `m_CorrectedPose` so you're just cutting out the middleman. 

---

Ok, I understand your logic now, I think we just need to create a transform function so that we're not messing with the internal data of the scan object _just_ to get a transform.

Comment (WLwind) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: I understand what you mean. I'll push a new commit soon.

Comment (WLwind) [reply slam_toolbox/lib/karto_sdk/src/Mapper.cpp]: > > L1609 and L1610 calculate that base pose we need which is passed to LinkInfo below.
> 
> I totally understand that, but I'm a little concerned by the fact that you're `setting` the pose, overriding whatever was there beforehand to compute this value (though 1611 resets). Would it not be possible to just [transform the data](https://github.com/SteveMacenski/slam_toolbox/blob/b0800ed7e5b1f955386a46a0ac8f9ef159120c13/slam_toolbox/lib/karto_sdk/include/karto_sdk/Karto.h#L5637-L5645) in the same way shown in that function without `Setting` / `Getting`?
> 
> Recommendation: Make [this logic](https://github.com/SteveMacenski/slam_toolbox/blob/b0800ed7e5b1f955386a46a0ac8f9ef159120c13/slam_toolbox/lib/karto_sdk/include/karto_sdk/Karto.h#L5637-L5646) into a function (or maybe an analog function to `GetSensorAt`, `GetCorrectedAt` will work?) that `SetSensorPose` uses. Then make that function public so that in L1609/1610 you can call that to replace the `set` and `get`. Then no data is messed with and we just transform some data.

I have pushed a new commit. Simplify setting `LinkInfo`.

**Comment by WLwind** [comment]
When I try localization mode with new code, every time loop closure comes, there comes a warning of ceres `CeresSolver: Ceres could not find a usable solution to optimize.`. So I think there is something I didn't consider.

**Comment by SteveMacenski** [comment]
The only difference I can tell is that old L1611 `SetCorrectedPose()` sets `m_CorrectedPose` but did not call `Update()` so from your pose-swapping, the values might be different? Also in `SetCorrectedPose()` it sets `m_IsDirty = true` but I don't think that should cause something. Both of those would serialize though for a localization session. 

Did you check the inputs / outputs of the new function to make sure its working properly? If mapping works OK and just localization, I feel like it does, but just checking. I highly doubt its the issue, but also try removing `inline`. Maybe after serialization that's making something unhappy.

**Comment by WLwind** [comment]
> The only difference I can tell is that old L1611 `SetCorrectedPose()` sets `m_CorrectedPose` but did not call `Update()` so from your pose-swapping, the values might be different? Also in `SetCorrectedPose()` it sets `m_IsDirty = true` but I don't think that should cause something. Both of those would serialize though for a localization session.
> 
> Did you check the inputs / outputs of the new function to make sure its working properly? If mapping works OK and just localization, I feel like it does, but just checking. I highly doubt its the issue, but also try removing `inline`. Maybe after serialization that's making something unhappy.

I mean b0800ed7e5b1f955386a46a0ac8f9ef159120c13, not just 5cb6690a17ee4ecb347f4c70de668e552f499aef.
Both of them show warning `CeresSolver: Ceres could not find a usable solution to optimize.` in localization mode. But 5cb6690a17ee4ecb347f4c70de668e552f499aef shows more:
`W0206 02:13:16.236030 10238 parameter_block.h:349] Local parameterization Jacobian computation returnedan invalid matrix for x: -nan
 Jacobian matrix : -nan`
I think the problem is from deserialization. Because when I tried to make that "1 line change" to make sensor poses as ceres nodes, the deserialization process threw an exception `terminate called after throwing an instance of 'karto::Exception'`. For this reason I switched to another way, making constraints between 2 base poses. Although it doesn't threw exceptions during deserialization now, I still think that there might be some faults.

**Comment by SteveMacenski** [comment]
To repeat that back to you, you think this change makes the serialized data wrong so things are failing? that would make sense, we're messing with things at a somewhat low level. ABI breaking changes like this might impact any data you've previously recorded, but its necessary to fix the bug. 

What happens if you run it over a newly generated serialized file done with the code in this PR after the change?

**Comment by WLwind** [comment]
Firstly I tried to find the problem with deserialization when I use "1 line change" solution, and (after adding lots of print function) I found that the problem is from `addNode`. The function need to `GetCorrectedPose` and it calls `GetLaserRangeFinder`. But I don't think the LaserRangeFinder is correctly set before deserialization in localization mode. So I think that is what makes the program throw the exception.
Let's go back to "all base pose" strategy. I've carefully compared the differences between 5cb6690a17ee4ecb347f4c70de668e552f499aef and the original code 44c9f840b01b1c9b5ed351c7d0074c641ee3e21c and the main difference is in `MapperGraph::CorrectPoses()`. When it calls `SetSensorPose` it does an `Update()` after setting the pose, but `SetCorrectedPose` doesn't do that updating. I added the update and test with the dataset with mapping and localization mode. There was nothing new with mapping (18 loop closures). The localization mode made 9 loop closures but only 1 popped the warning `CeresSolver: Ceres could not find a usable solution to optimize.`. I can clearly see some loop closures optimizing the "walls", so I think this new commit solves the problem with localization mode mostly. It's workable now.

**Comment by SteveMacenski** [comment]
I don't understand why calling Update would change Ceres's ability to find a solution. Update is messing with the point values and resetting `m_isDirty`. It seems like is dirty is the major issue but every time we try to access the dirty info, there's a check and update is called anyhow in the object https://github.com/SteveMacenski/slam_toolbox/blob/171f28236aac12d7a66a3d23eeeb5a88d1ca2658/slam_toolbox/lib/karto_sdk/include/karto_sdk/Karto.h#L5503

Does `CeresSolver: Ceres could not find a usable solution to optimize.` pop up when using a new serialized file from this current set of code? I suspect that it now has nothing to do with `Update()` if it happens on occasion and more do with this change `pEdge->SetLabel(new LinkInfo(pFromScan->GetCorrectedPose(), pToScan->GetCorrectedAt(rMean), rCovariance));` since the graph now would have data in it assuming `rMean` and then new data that is `pToScan->GetCorrectedAt(rMean)`. If it goes away from new serialized data, then I think we're good. If it still appears, that's still a problem we need to solve.

A single small dataset of 9 loop closures having it appear once might not be the worst-case situation. I don't think it was happening at all prior. If we have new serialized files with the new code, then it should be acting at least as good as before in localization mode if we did everything correctly, yes?

**Comment by SteveMacenski** [comment]
@WLwind any update? Just trying to iterate on the best solution to this issue so that it doesn't come back and bite you

**Comment by WLwind** [comment]
> @WLwind any update? Just trying to iterate on the best solution to this issue so that it doesn't come back and bite you

I'm busy these days and have little time to consider about this issue, sorry.

**Comment by SteveMacenski** [comment]
Closed the other 2 PRs since we're still working on getting this one passing completely

**Comment by WLwind** [comment]
Thank you for testing! I really don't have time to test it these weeks.

**Comment by SteveMacenski** [comment]
Thanks for identifying this issue so we can finally put this issue to bed!
