### PR TITLE
Fix map_start_at_dock & map_start_at_dock parsing

### LINKED ISSUE #842: map_start_pose is always set when posegraph is given
- Operating System:
  - Docker, ros:jazzy-ros-base
- Installation type:
  - binaries 
- ROS Version
  - jazzy
  
When starting async_slam_toolbox_node with a posegraph given as map_file_name and parameter
- map_start_pose is not set
- map_start_at_dock = True

the node does ignore map_start_at_dock and will print this error:
> LocalizationSlamToolbox: Incorrect number of arguments for map starting pose. Must be in format: [x, y, theta]. Starting at the origin

Cause is probably in [slam_toolbox_common.cpp#L626](https://github.com/SteveMacenski/slam_toolbox/blob/3661355d9560cd086339d6cd4738915734c7b939/src/slam_toolbox_common.cpp#L626):
```
  if (!this->has_parameter("map_start_pose")) {
    this->declare_parameter("map_start_pose", std::vector<double>());
  }
```
where map_start_pose is always set to en empty array if not set. So in [slam_toolbox_common.cpp#L640](https://github.com/SteveMacenski/slam_toolbox/blob/3661355d9560cd086339d6cd4738915734c7b939/src/slam_toolbox_common.cpp#L640) the following check is always true:
```
if (map_start_pose.get_type() != rclcpp::ParameterType::PARAMETER_NOT_SET) {
```

possible fix: Change the if condition in line 640 to check for empty array

### PR DESCRIPTION
**Pull request by nxdefiant**
Due to the default initialization with declare_parameter the type is never PARAMETER_NOT_SET so change detection of unset map_start_pose by checking for size=0

Fixes #842

tested variants:
- map_start_at_dock unset/false, map_start_pose unset => log error, ok
- map_start_at_dock=unset/false/true, map_start_pose set valid => map_start_pose used, ok
- map_start_at_dock=true => start at first pose, ok
- map_start_pose with only two elements => log error, ok

### CODE REVIEW

File: src/slam_toolbox_common.cpp [hunk 1]
```diff
@@ -630,15 +630,18 @@ bool SlamToolbox::shouldStartWithPoseGraph(
...
-  auto map_start_at_dock = this->get_parameter("map_start_at_dock").get_parameter_value();
+  start_at_dock = this->get_parameter("map_start_at_dock").as_bool();
   if (!this->has_parameter("map_file_name")) {
     this->declare_parameter("map_file_name", std::string(""));
   }
   filename = this->get_parameter("map_file_name").as_string();
   if (!filename.empty()) {
     std::vector<double> read_pose;
-    if (map_start_pose.get_type() != rclcpp::ParameterType::PARAMETER_NOT_SET) {
+    if (map_start_pose.get_type() == rclcpp::ParameterType::PARAMETER_DOUBLE_ARRAY) {
```
Comment (SteveMacenski) [inline src/slam_toolbox_common.cpp]: It should always be a parameter double array  - else `map_start_pose` would have thrown an exception already since the default value / type is set at such.

Comment (nxdefiant) [reply src/slam_toolbox_common.cpp]: Do you want me to drop this check?

Comment (SteveMacenski) [reply src/slam_toolbox_common.cpp]: Yeah just get the parameter

Comment (SteveMacenski) [reply src/slam_toolbox_common.cpp]: This looks like quite the mess, I tihnk the port to ROS 2 was not done super well in this part of the code

**Review by SteveMacenski — APPROVED** [review]
